/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arff_conversion;

import java.io.IOException;
import java.util.Arrays;
import java.util.stream.Stream;

import com.google.common.io.Files;

import weka.core.Instances;
import weka.core.converters.ArffLoader;
import weka.core.converters.JSONSaver;
import weka.core.converters.ConverterUtils.DataSink;
import weka.core.converters.ConverterUtils.DataSource;
import java.io.File;

public class ArffConverter {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

       for (String arg : args) {
        ArffLoader loader = new ArffLoader();
        try {

        File f = new File(arg); 
        loader.setFile(f);
        DataSource  ds = new DataSource(loader);
        Instances i = ds.getDataSet(); 
        JSONSaver js_saver = new JSONSaver();
        File outFIle =     new File( f.getParent() + "/" + Files.getNameWithoutExtension(arg) + ".json"); 
        js_saver.setFile(outFIle);     
        System.out.println("i have " + i.numInstances() + " instances");
        System.out.println("Saved to" + outFIle.toString());
        DataSink.write(js_saver, i);
        }   
        catch (IOException e) {
            System.out.println("error IO");
        }
        catch (Exception e) {
            System.out.println("error e");
        }

       }

        System.out.println(new ArffConverter().getGreeting());
    }
}
